module.exports = {
  apps: [
    {
      name: "saas-api",
      cwd: "./apps/api",
      script: "npm",
      args: "start",
      instances: "max",
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        API_PREFIX: "api",
      },
      env_development: {
        NODE_ENV: "development",
        PORT: 3001,
        API_PREFIX: "api",
      },
      exp_backoff_restarts: true,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
      error_file: "logs/saas-api-error.log",
      out_file: "logs/saas-api-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      ignore_watch: ["node_modules", ".git", "logs", ".next"],
    },
    {
      name: "saas-web",
      cwd: "./apps/web",
      script: "npm",
      args: "start",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        NEXT_PUBLIC_API_URL: "http://localhost:3001",
      },
      max_memory_restart: "256M",
      min_uptime: "10s",
      max_restarts: 10,
      error_file: "logs/saas-web-error.log",
      out_file: "logs/saas-web-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      ignore_watch: ["node_modules", ".git", "logs", ".next", "src"],
    },
  ],
};
