module.exports = {
  apps: [
    {
      name: "saas-api",
      cwd: "./apps/api",
      script: "dist/apps/api/src/main.js",
      instances: "max",
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3001,
        API_PREFIX: "api",
        FRONTEND_URL: "http://localhost:3000",
        JWT_SECRET: "dev-secret-change-me",
        JWT_ACCESS_EXPIRES_IN: "15m",
        JWT_REFRESH_EXPIRES_IN: "30d",
        DB_TYPE: "postgres",
        DB_HOST: "localhost",
        DB_PORT: "5432",
        DB_USERNAME: "saas",
        DB_PASSWORD: "saas",
        DB_DATABASE: "saas",
        DB_SYNCHRONIZE: "false",
        DB_LOGGING: "false",
        REDIS_HOST: "localhost",
        REDIS_PORT: "6379",
        EMAIL_PROVIDER: "console",
        EMAIL_FROM: "no-reply@saas.dev",
        FREE_PROJECT_LIMIT: "3",
        STORAGE_PROVIDER: "local",
        STORAGE_LOCAL_DIR: "./uploads",
        STORAGE_BASE_URL: "http://localhost:3001/files",
        CORS_ALLOWED_ORIGINS: "http://localhost:3000",
        CSRF_ENABLED: "false",
        RATE_LIMIT_TTL: "60000",
        RATE_LIMIT_GLOBAL_LIMIT: "120",
        RATE_LIMIT_AUTH_LIMIT: "10",
        RATE_LIMIT_STRICT_LIMIT: "30",
        SESSION_DEVICE_BINDING: "false",
      },
      env_development: {
        NODE_ENV: "development",
        PORT: 3001,
        API_PREFIX: "api",
      },
      wait_ready: false,
      listen_timeout: 30000,
      kill_timeout: 30000,
      shutdown_with_message: true,
      exp_backoff_restarts: true,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
      error_file: "logs/saas-api-error.log",
      out_file: "logs/saas-api-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      ignore_watch: ["node_modules", ".git", "logs", ".next", "src", "dist"],
    },
    {
      name: "saas-web",
      cwd: "./apps/web",
      script: "/usr/bin/npx",
      args: "next start -p 3000",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        NEXT_PUBLIC_API_URL: "http://localhost:3001",
      },
      wait_ready: false,
      listen_timeout: 30000,
      kill_timeout: 30000,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
      error_file: "logs/saas-web-error.log",
      out_file: "logs/saas-web-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      ignore_watch: ["node_modules", ".git", "logs", ".next", "src"],
    },
  ],
};
